# Generated by Django 5.2.9 on 2025-12-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='MenuItem',
        ),
    ]
