# Generated by Django 5.2.9 on 2026-01-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizers'), ('main', 'Main Courses'), ('dessert', 'Desserts')], default='main', max_length=20),
        ),
    ]
