# Generated by Django 5.2.9 on 2026-01-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_menuitem_image_menuitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
