# Generated by Django 5.2.9 on 2026-01-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_menuitem_image_url_menuitem_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
